#Server APP
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: server
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: alejo88/titulacion-prod
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    env: prod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    env: prod
